title: "Embeded Projects"
description: ""
remote_theme: "jekyll/minima@1e8a445"
plugins:
  - jekyll-relative-links

relative_links:
  enabled:     true
  collections: false
  exclude:
    - ./obsidian

